name: Build and Create DMG

on:
  push:
    branches:
      - releases

jobs:
  build:
    name: Build and Package
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build App
        # Builds the app in Release mode using Ad-Hoc signing (no Apple ID required)
        run: |
          xcodebuild \
            -project DontDuckWithMyMac.xcodeproj \
            -scheme DontDuckWithMyMac \
            -configuration Release \
            -derivedDataPath ./build \
            clean build \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED="NO" \
            CODE_SIGNING_ALLOWED="NO"

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG Installer
        # Uses create-dmg to package the .app into a nice drag-and-drop installer
        run: |
          cd build/Build/Products/Release
          create-dmg \
            --volname "DontDuck Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "DontDuckWithMyMac.app" 200 190 \
            --hide-extension "DontDuckWithMyMac.app" \
            --app-drop-link 600 185 \
            "DontDuckWithMyMac.dmg" \
            "DontDuckWithMyMac.app"

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DontDuckWithMyMac-Installer
          path: build/Build/Products/Release/DontDuckWithMyMac.dmg
